apiVersion: v1
kind: Service
metadata:
  name: smartinvite-api
  namespace: {{ .Values.namespace }}
  labels:
    app: smartinvite-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: smartinvite-api
