apiVersion: v1
kind: Service
metadata:
  name: invitelink-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: invitelink-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: invitelink-frontend
